name = "vault_doctor"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
gleam_json = ">= 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
plinth = ">= 0.8.2 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
